version: "3.8"

services:
  blog-api:
    container_name: api-blog
    build: .
    command: npm run start
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: docker
      DB_PASSWORD: docker
      DB_NAME: blog-api-db
    depends_on:
      - postgres

  postgres:
    container_name: blog-api-pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: blog-api-db

  # cache:
  #   container_name: blog-api-cache
  #   image: redis
  #   ports:
  #     - 6379:6379
  #   volumes:
  #     - ./data/redis:/data
