version: "3.8"

services:
  blog-api:
    container_name: api-blog
    build: .
    command: npm run start
    ports:
      - 3000:3000
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    environment:
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - postgres

  postgres:
    container_name: blog-api-pg
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: blog-api-db
    ports:
      - 5432:5432

  cache:
    container_name: blog-api-cache
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
